name: Test workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies, make test-coverage
        run: |
          npm install
          make test-coverage

      - name: Run tests
        run: npm test
        
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
          github-token: ${{ secrets.GITHUB_TOKEN }}
